---
abstract: 'Part of the test framework for Alien::Base'
author:
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  Acme::Alien::DontPanic: 0.003
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Ford-Prefect
provides:
  Acme::Ford::Prefect:
    file: lib/Acme/Ford/Prefect.pm
    version: 0.003
requires:
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
version: 0.003
